Create SIMD-09-30.md
WebAssembly/meetings pull request #1122
Opened 2022-09-30 17:45 UTC by penzn

2022-09-30 17:49 UTC, penzn commented
I don't seem to be able to add reviewers. @conrad-watt wanted to review the summary comment. Also @dtig, @yurydelendik, @justinmichaud, @Maratyszcza, @abrown, please take a look.

2022-09-30 18:25 UTC, Maratyszcza approved these changes

2022-10-05 18:39 UTC, penzn commented
@dtig did you get any better transcription?

In case there are no further changes, I think we should merge this.

By the way, on the issue of adding reviewers, I think Github has a contributor role without write access, that should allow for requesting reviews. It would be good if all subgroup (co)chairs had at least that role for this repo ;)  (/CC @dschuff)

2022-10-06 21:50 UTC, penzn commented
I made some minor changes, I think it should be ready to merge.

2022-10-06 21:52 UTC, ngzhian requested changes

2022-10-07 00:24 UTC, penzn commented on simd/2022/SIMD-09-30.md
> +MD: Dood on my side. I implemented optimizations using relaxed-simd in xnnpack, got very good speedup
~Dood~Good catch

2022-10-07 00:25 UTC, penzn commented
Thanks for review @ngzhian, also caught a couple more typos after

2022-10-11 19:02 UTC, penzn commented
ping @ngzhian

2022-10-11 19:37 UTC, ngzhian approved these changes

2022-10-11 21:37 UTC, merged