Add an item for simple proposals to 2021-09-28
WebAssembly/meetings pull request #880
Opened 2021-09-21 21:06 UTC by penzn

For #857

2021-09-21 21:07 UTC, penzn commented
/CC @dtig

2021-09-22 17:18 UTC, dtig requested changes
Thanks @penzn! Could you also time box this discussion?

2021-09-22 23:43 UTC, penzn commented
Done.

2021-09-23 04:23 UTC, dtig approved these changes

2021-09-23 04:24 UTC, merged